---
title: "Lobster MPA Fishery Spillover"
author: "Eva Juengling Bean, Nils Boberg, Grace Bryan"
format: html
editor: visual
---

```{r}
#| label: load-libraries
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(here)
library(janitor)
library(ggplot2)

```

```{r}
#| label: source-functions
#| echo: true 

source(here("R/calculate_k.R")) # source module 1
source(here("R/calc_pop_change.R")) # source module 2
source(here("R/calc_migration.R")) # source module 3
source(here("R/calc_catch.R")) # source module 4
source(here("R/calc_MPA_cost.R")) # source module 7
source(here("R/calc_net_profit.R")) # source module 6

```

```{r}
#| label: create-data
#| echo: true

mpa_area <- seq(5, 50, by=5)
data <- as.data.frame(mpa_area)
data$k <- NA
data$n_in <- NA
data$n_out <- NA
data$catch <- NA
data$cost <- NA
data$net_profit <- NA
data$k_fishing <- NA

```

```{r}
#| label: run-program
#| echo: true

for (i in 1:length(mpa_area)){
  data$k[i]=calculate_k(mpa_area=data$mpa_area[i])
  
  data$k_fishing[i] <- calculate_k(mpa_area = data$mpa_area[i] * 2) # simply assumes fishing area is twice the MPA size
  
  data$n_in[i]=calc_pop_change(k=data$k[i])
  
  data$n_out[i]=calc_migration(n_t_in=data$n_in[i])
  
  data$catch[i]=calc_catch(n_t_out=data$n_out[i])
  
  data$cost[i] <- calc_MPA_cost(mpa_area = data$mpa_area[i])
  
  data$net_profit[i] <- calc_net_profit(catch = data$catch[i], cost = data$cost[i])
  
}
```

```{r}
#| label: plot
#| echo: true

net_profit_plot <- ggplot(data, aes(x=mpa_area,y=net_profit))+
  geom_line()+
  geom_point()+
  xlab("MPA Area")+
  ylab("Net Profit ($)")+
  theme_bw()

net_profit_plot
```
